version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: train-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: train-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/traindb?authSource=admin
      PORT: 5000
      FRONTEND_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: train-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      # Leave REACT_APP_API_URL blank so the frontend's nginx can proxy /api to backend
      - REACT_APP_API_URL=

volumes:
  mongodb_data:
